#!/usr/bin/env python3
"""
Script to create an example threat model and run tmi_tf analysis on it.

This script:
1. Creates a threat model named "Example: AI Automated Terraform Template Analysis"
2. Adds the oracle-devrel/terraform-oci-arch-web-ha GitHub repository to it
3. Runs the tmi_tf analyze command on the threat model
"""

import sys
import subprocess
from pathlib import Path

# Add the tmi-tf package to the path
tmi_tf_path = Path(__file__).parent
sys.path.insert(0, str(tmi_tf_path))

# Add tmi-client to path (same as tmi_client_wrapper does)
tmi_client_path = Path.home() / "Projects" / "tmi-clients" / "python-client-generated"
if tmi_client_path.exists():
    sys.path.insert(0, str(tmi_client_path))
else:
    print(f"Error: TMI Python client not found at {tmi_client_path}")
    sys.exit(1)

from tmi_tf.config import get_config  # noqa: E402
from tmi_tf.tmi_client_wrapper import TMIClient  # noqa: E402
from tmi_client.models import ThreatModelInput, RepositoryInput  # noqa: E402


def create_example_threat_model(force_auth=False):
    """Create the example threat model and add repository."""
    print("🔧 Loading configuration...")
    config = get_config()

    print("🔐 Authenticating with TMI...")
    tmi_client = TMIClient.create_authenticated(config, force_refresh=force_auth)

    print("📝 Creating threat model...")
    threat_model_input = ThreatModelInput(
        name="Example: AI Automated Terraform Template Analysis",
        description=(
            "This is an example threat model that was generated by adding a link to a repository "
            "containing Terraform templates, and then running the TMI-TF (https://github.com/ericfitz/tmi-tf) "
            "tool against it. All analysis and analysis products - diagrams, notes, and threats - "
            "were created by AI."
        ),
    )

    threat_model = tmi_client.threat_models_api.create_threat_model(
        body=threat_model_input
    )

    threat_model_id = threat_model.id
    print(f"✅ Created threat model with ID: {threat_model_id}")
    print(f"   Name: {threat_model.name}")

    print("\n📦 Adding repository to threat model...")
    repo_input = RepositoryInput(
        name="Oracle Cloud Web HA Terraform",
        description="Terraform templates for highly available web application on Oracle Cloud Infrastructure",
        type="git",
        uri="https://github.com/oracle-devrel/terraform-oci-arch-web-ha.git",
        parameters={"branch": "main"},
    )

    repository = tmi_client.sub_resources_api.create_threat_model_repository(
        body=repo_input, threat_model_id=threat_model_id
    )

    print(f"✅ Added repository: {repository.uri}")
    if hasattr(repository, "id"):
        print(f"   Repository ID: {repository.id}")

    return threat_model_id


def run_tmi_tf_analysis(threat_model_id):
    """Run the tmi_tf analyze command on the threat model."""
    print(f"\n🔍 Running tmi_tf analysis on threat model {threat_model_id}...")
    print("=" * 80)

    # Run tmi_tf analyze using subprocess
    cmd = ["uv", "run", "tmi_tf", "analyze", threat_model_id, "--verbose"]

    print(f"Executing: {' '.join(cmd)}\n")

    try:
        result = subprocess.run(
            cmd,
            cwd=tmi_tf_path,
            check=True,
            text=True,
            capture_output=False,  # Show output in real-time
        )
        print("\n" + "=" * 80)
        print("✅ Analysis completed successfully!")
        return result.returncode
    except subprocess.CalledProcessError as e:
        print("\n" + "=" * 80)
        print(f"❌ Analysis failed with exit code {e.returncode}")
        return e.returncode


def main():
    """Main entry point."""
    print("🚀 Starting Example Threat Model Creation and Analysis")
    print("=" * 80)

    # Check for --force-auth flag
    force_auth = "--force-auth" in sys.argv

    try:
        # Step 1: Create threat model and add repository
        threat_model_id = create_example_threat_model(force_auth=force_auth)

        # Step 2: Run tmi_tf analysis
        exit_code = run_tmi_tf_analysis(threat_model_id)

        print("\n" + "=" * 80)
        print("🎉 All steps completed!")
        print(f"   Threat Model ID: {threat_model_id}")
        print(f"   Exit Code: {exit_code}")

        return exit_code

    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback

        traceback.print_exc()
        return 1


if __name__ == "__main__":
    sys.exit(main())
