#!/usr/bin/env python3
"""
Script to create an example threat model using CLI tools and then analyze it.

This script:
1. Creates a threat model using the TMI API
2. Adds a repository to it
3. Runs the tmi_tf analyze command on the threat model

This version uses direct API calls through requests for creating the threat model,
then calls the tmi_tf CLI for analysis.
"""

import json
import subprocess
import sys
from pathlib import Path


def load_token():
    """Load the cached TMI token."""
    token_file = Path.home() / ".tmi-tf" / "token.json"
    if not token_file.exists():
        print(f"❌ No token found at {token_file}")
        print("   Please run: uv run python -m tmi_tf.cli auth")
        sys.exit(1)

    with open(token_file) as f:
        token_data = json.load(f)

    return token_data.get("token")


def create_threat_model_via_api(token, server_url="https://api.tmi.dev"):
    """Create threat model using direct API call."""
    import requests  # ty:ignore[unresolved-import]

    print("📝 Creating threat model...")

    headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}

    payload = {
        "name": "Example: AI Automated Terraform Template Analysis",
        "description": (
            "This is an example threat model that was generated by adding a link to a repository "
            "containing Terraform templates, and then running the TMI-TF (https://github.com/ericfitz/tmi-tf) "
            "tool against it. All analysis and analysis products - diagrams, notes, and threats - "
            "were created by AI."
        ),
    }

    response = requests.post(
        f"{server_url}/threat_models", headers=headers, json=payload
    )

    if response.status_code != 201:
        print(f"❌ Failed to create threat model: {response.status_code}")
        print(f"   Response: {response.text}")
        sys.exit(1)

    threat_model = response.json()
    threat_model_id = threat_model["id"]

    print(f"✅ Created threat model with ID: {threat_model_id}")
    print(f"   Name: {threat_model['name']}")

    return threat_model_id


def add_repository_to_threat_model(
    token, threat_model_id, server_url="https://api.tmi.dev"
):
    """Add repository to threat model using direct API call."""
    import requests  # ty:ignore[unresolved-import]

    print("\n📦 Adding repository to threat model...")

    headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}

    payload = {
        "name": "Oracle Cloud Web HA Terraform",
        "description": "Terraform templates for highly available web application on Oracle Cloud Infrastructure",
        "type": "git",
        "uri": "https://github.com/oracle-devrel/terraform-oci-arch-web-ha.git",
        "parameters": {"refType": "branch", "refValue": "main"},
    }

    response = requests.post(
        f"{server_url}/threat_models/{threat_model_id}/repositories",
        headers=headers,
        json=payload,
    )

    if response.status_code != 201:
        print(f"❌ Failed to add repository: {response.status_code}")
        print(f"   Response: {response.text}")
        sys.exit(1)

    repository = response.json()
    print(f"✅ Added repository: {repository['uri']}")
    if "id" in repository:
        print(f"   Repository ID: {repository['id']}")

    return repository


def run_tmi_tf_analysis(threat_model_id):
    """Run the tmi_tf analyze command on the threat model."""
    print(f"\n🔍 Running tmi_tf analysis on threat model {threat_model_id}...")
    print("=" * 80)

    # Run tmi_tf analyze using subprocess
    cmd = [
        "uv",
        "run",
        "python",
        "-m",
        "tmi_tf.cli",
        "analyze",
        threat_model_id,
        "--verbose",
        "--force-auth",
    ]

    print(f"Executing: {' '.join(cmd)}\n")

    try:
        result = subprocess.run(
            cmd,
            check=True,
            text=True,
            capture_output=False,  # Show output in real-time
        )
        print("\n" + "=" * 80)
        print("✅ Analysis completed successfully!")
        return result.returncode
    except subprocess.CalledProcessError as e:
        print("\n" + "=" * 80)
        print(f"❌ Analysis failed with exit code {e.returncode}")
        return e.returncode


def main():
    """Main entry point."""
    print("🚀 Starting Example Threat Model Creation and Analysis")
    print("=" * 80)

    try:
        # Step 0: Load authentication token
        print("🔐 Loading authentication token...")
        token = load_token()
        print("✅ Token loaded")

        # Step 1: Create threat model
        threat_model_id = create_threat_model_via_api(token)

        # Step 2: Add repository
        add_repository_to_threat_model(token, threat_model_id)

        # Step 3: Run tmi_tf analysis
        exit_code = run_tmi_tf_analysis(threat_model_id)

        print("\n" + "=" * 80)
        print("🎉 All steps completed!")
        print(f"   Threat Model ID: {threat_model_id}")
        print(f"   Exit Code: {exit_code}")

        return exit_code

    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback

        traceback.print_exc()
        return 1


if __name__ == "__main__":
    sys.exit(main())
