"""
Markdown report generator for Lambda webhook-triggered analysis.

This module wraps the original markdown generation with webhook-specific metadata
to create user-facing execution logs in TMI notes.
"""

import logging
from datetime import datetime
from typing import Dict, Any, Optional

logger = logging.getLogger(__name__)


def generate_webhook_report(
    threat_model_id: str,
    repository: Any,  # tmi_client.Repository object
    analysis_content: str,
    webhook_metadata: Dict[str, Any],
    lambda_request_id: Optional[str] = None,
    error: Optional[Exception] = None
) -> str:
    """
    Generate markdown report with webhook execution metadata.

    This creates a user-facing log that shows:
    - What triggered the analysis (webhook event)
    - When it was executed
    - Repository analyzed
    - Success/failure status
    - Detailed analysis results

    Args:
        threat_model_id: Threat model UUID
        repository: Repository object being analyzed
        analysis_content: Markdown content from Claude analysis
        webhook_metadata: Webhook event data (delivery_id, event_type, timestamp)
        lambda_request_id: AWS Lambda request ID for debugging
        error: Optional exception if analysis failed

    Returns:
        Formatted markdown report with webhook metadata
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")
    event_type = webhook_metadata.get('event_type', 'unknown')
    delivery_id = webhook_metadata.get('delivery_id', 'unknown')
    webhook_timestamp = webhook_metadata.get('timestamp', 'unknown')

    # Determine status
    if error:
        status_badge = "❌ **FAILED**"
        status_section = f"""
## ⚠️ Analysis Failed

**Error**: {str(error)}

**Error Type**: {type(error).__name__}

### Troubleshooting Steps

1. **Check CloudWatch Logs**: Search for Lambda request ID: `{lambda_request_id}`
2. **Verify Repository Access**: Ensure the repository is accessible and contains Terraform files
3. **Check TMI API**: Verify TMI API is operational
4. **Review Lambda Configuration**: Check IAM permissions and environment variables

### Next Actions

- If this is a temporary issue (API timeout, network), the analysis will be retried automatically
- If the repository has issues, update the repository and trigger re-analysis
- For persistent errors, contact support with the Lambda request ID above
"""
    else:
        status_badge = "✅ **SUCCESS**"
        status_section = ""

    # Build markdown report
    report = f"""# Terraform Analysis: {repository.name}

{status_badge}

---

## 📋 Analysis Metadata

| Field | Value |
|-------|-------|
| **Threat Model ID** | `{threat_model_id}` |
| **Repository** | [{repository.url}]({repository.url}) |
| **Repository ID** | `{repository.id}` |
| **Analysis Date** | {timestamp} |
| **Triggered By** | Webhook Event (`{event_type}`) |
| **Webhook Delivery ID** | `{delivery_id}` |
| **Webhook Timestamp** | {webhook_timestamp} |
| **Analysis Engine** | Claude Sonnet 4.5 (AWS Lambda) |
| **Lambda Request ID** | `{lambda_request_id}` |

---

"""

    if error:
        # Error report
        report += status_section
    else:
        # Success report with analysis content
        report += f"""## 🔍 Analysis Results

{analysis_content}

---

## ℹ️ About This Analysis

This report was automatically generated by the TMI Terraform Analyzer Lambda function in response to a `{event_type}` webhook event.

The analysis uses Claude Sonnet 4.5 to examine Terraform infrastructure-as-code and identify:
- Security vulnerabilities and misconfigurations
- Best practice violations
- Resource dependencies and data flows
- Potential threat model implications

**How it works**:
1. TMI webhook event triggers Lambda function
2. Repository is cloned with sparse checkout (Terraform files only)
3. Claude AI analyzes infrastructure code
4. Results are automatically added to this threat model

**Need help?** Contact your security team or check the TMI documentation.

---

**Generated**: {timestamp} | **Event ID**: `{delivery_id}` | **Request ID**: `{lambda_request_id}`
"""

    return report


def generate_error_report(
    threat_model_id: str,
    repository: Any,
    error: Exception,
    webhook_metadata: Dict[str, Any],
    lambda_request_id: Optional[str] = None
) -> str:
    """
    Generate error report for failed analysis.

    Args:
        threat_model_id: Threat model UUID
        repository: Repository object that failed to analyze
        error: Exception that occurred
        webhook_metadata: Webhook event data
        lambda_request_id: AWS Lambda request ID

    Returns:
        Formatted markdown error report
    """
    return generate_webhook_report(
        threat_model_id=threat_model_id,
        repository=repository,
        analysis_content="",
        webhook_metadata=webhook_metadata,
        lambda_request_id=lambda_request_id,
        error=error
    )
